name = "conformance"


[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
hegel_gleam = { path = ".." }
envoy = ">= 1.2.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
